// <auto-generated />
namespace IOT_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class E_Data2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(E_Data2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104011019354_E_Data2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
